use std::env;
use std::fs;
use std::io::{self, Write};
use std::path::Path;

const METAL_SOURCES: &[&str] = &[
    "flash_attn.metal", "dense.metal", "moe.metal", "dsv4_hc.metal",
    "unary.metal", "dsv4_kv.metal", "dsv4_rope.metal", "dsv4_misc.metal",
    "argsort.metal", "cpy.metal", "concat.metal", "get_rows.metal",
    "sum_rows.metal", "softmax.metal", "repeat.metal", "glu.metal",
    "norm.metal", "bin.metal", "set_rows.metal",
];

fn main() -> io::Result<()> {
    let manifest_dir_str = env::var("CARGO_MANIFEST_DIR").unwrap();
    let manifest_dir = Path::new(&manifest_dir_str);
    let parent = manifest_dir.parent().unwrap();

    // ── Embed Metal shader sources ─────────────────────────────────
    let out_dir_str = env::var("OUT_DIR").unwrap();
    let out_dir = Path::new(&out_dir_str);
    let out_path = out_dir.join("metal_sources.rs");
    let metal_dir = parent.join("metal");

    let mut out = fs::File::create(&out_path)?;
    writeln!(out, "// Auto-generated by build.rs")?;
    writeln!(out)?;
    for (i, name) in METAL_SOURCES.iter().enumerate() {
        let path = metal_dir.join(name);
        println!("cargo:rerun-if-changed={}", path.display());
        let contents = fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("failed to read {}: {}", path.display(), e));
        let const_name = name.replace('.', "_").replace('-', "_").to_uppercase();
        let const_name = const_name.strip_suffix("_METAL").unwrap_or(&const_name);
        writeln!(out, "pub const METAL_{i:02}_{const_name}: &str = r###\"", i = i, const_name = const_name)?;
        let safe = contents.replace("###", "##\x03#");
        writeln!(out, "{}", safe)?;
        writeln!(out, "\"###;")?;
        writeln!(out)?;
    }
    write!(out, "pub const METAL_SOURCE_SLICE: &[&str] = &[")?;
    for i in 0..METAL_SOURCES.len() {
        let name = METAL_SOURCES[i].replace('.', "_").replace('-', "_").to_uppercase();
        let const_name = name.strip_suffix("_METAL").unwrap_or(&name);
        write!(out, "METAL_{i:02}_{const_name}, ", i = i, const_name = const_name)?;
    }
    writeln!(out, "];")?;

    // ── Compile C engine + Metal backend ───────────────────────────
    let mut build = cc::Build::new();
    build
        .file(parent.join("ds4.c"))
        .file(parent.join("ds4_metal.m"))
        .include(parent)
        .opt_level(3)
        .flag("-ffast-math")
        .flag("-std=c99")
        .flag("-fobjc-arc")
        .flag_if_supported("-mcpu=native")
        .warnings(true);
    build.compile("ds4");

    // Link frameworks
    println!("cargo:rustc-link-lib=framework=Foundation");
    println!("cargo:rustc-link-lib=framework=Metal");

    Ok(())
}
